### ISSUE TITLE
error: File not part of module ...

### ISSUE THREAD

**Issue by blake256** [samlitowitz/goimportcycle#2]
Whatever I try the following error is displayed:

```
anon@ubuntu:~/Projects/test/goimportcycle$ ~/go/bin/goimportcycle -path examples/importcycle/ -dot imports.dot
2022/05/17 15:25:01 File not part of module github.com/samlitowitz/goimportcycle
```

**Comment by SimonTheLeg** [comment]
Can reproduce this error.

Also tried building from master directly, as well as from git tags for v1.0.4 and v1.0.3, resulting in the same.

```sh
❯ go version
go version go1.18.2 darwin/amd64
```

**Comment by samlitowitz** [comment]
This is caused by not having the directory match the go module. If you move the directory from `/tmp/goimportcycle` to /tmp/github.com/samlitowitz/goimportcycle` you should not have this error. 

If you'd like to create a feature request issue to address this feel free but please note I currently consider this a low priority issue.
